name: Build Android and iOS
on: 
  pull request:
     branches:
      - developer
      - test
      - production  
  push:
    branches:
      - developer
      - test
      - production
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm test
